<a href="https://colab.research.google.com/github/drsubirghosh2008/drsubirghosh2008/blob/main/PW_Assignment_Module_17_28_10_24_Pandas_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Create a Pandas Series that contains the following data: 4, 8, 15, 16, 23, and 42. Then, print the series.

Answer:

In [2]:
import pandas as pd

# Creating a Pandas Series with the given data
data_series = pd.Series([4, 8, 15, 16, 23, 42])

# Printing the series
data_series

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

Q2. Create a variable of list type containing 10 elements in it, and apply pandas.Series function on the variable print it.

Answer:

In [3]:
# Creating a list with 10 elements
data_list = [3, 5, 9, 12, 18, 25, 31, 38, 47, 53]

# Converting the list to a Pandas Series
data_series_from_list = pd.Series(data_list)

# Printing the series
data_series_from_list

0     3
1     5
2     9
3    12
4    18
5    25
6    31
7    38
8    47
9    53
dtype: int64

Q3. Create a Pandas DataFrame that contains the following data:
Name           Age         Gender
Alice           25         Female
Bob             30         Male
Claire          27         Female

Then, print the DataFrame.

In [4]:
# Creating a DataFrame with the specified data
data_frame = pd.DataFrame({
    "Name": ["Alice", "Bob", "Claire"],
    "Age": [25, 30, 27],
    "Gender": ["Female", "Male", "Female"]
})

# Printing the DataFrame
data_frame

     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   27  Female

Q4. What is ‘DataFrame’ in pandas and how is it different from pandas.series? Explain with an example.

In Pandas, a DataFrame is a two-dimensional, size-mutable, and labeled data structure with columns of potentially different data types. It can be thought of as a table (like an Excel spreadsheet) with rows and columns, where each column represents a Pandas Series.

A Series, on the other hand, is a one-dimensional array-like structure that holds a single column of data with an associated index.

Key Differences:

Dimension: A DataFrame is two-dimensional (rows and columns), while a Series is one-dimensional.

Structure: A Series represents a single column of data, whereas a DataFrame is a collection of Series (multiple columns).

Data Types: A DataFrame can contain columns of different data types (e.g., integers, floats, strings), while a Series typically contains a single data type (although it can hold mixed types).

In [8]:
# Example: DataFrame
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Claire"],
    "Age": [25, 30, 27],
    "Gender": ["Female", "Male", "Female"]
})
print(df)

     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   27  Female

In [7]:
# Example: Series
age_series = pd.Series([25, 30, 27], name="Age")
print(age_series)

0    25
1    30
2    27
Name: Age, dtype: int64

In this example,

The DataFrame df contains multiple columns: "Name," "Age," and "Gender."
The Series age_series holds only a single column of data, representing ages, with no additional column for names or gender.

Q5. What are some common functions you can use to manipulate data in a Pandas DataFrame? Can you give an example of when you might use one of these functions?

Answer:

Pandas provides a wide range of functions for data manipulation in a DataFrame. Here are some common ones:

1. head() and tail(): View the first or last few rows of a DataFrame.

Example: df.head(5) displays the first 5 rows, useful for quickly inspecting data.

2. info(): Provides a concise summary of the DataFrame, showing the data types, non-null counts, and memory usage.

Example: Use df.info() to get a quick summary of the dataset’s structure, especially useful for identifying missing values.

3. describe(): Calculates summary statistics for numerical columns, including count, mean, standard deviation, min, and max.

Example: Use df.describe() to understand the distribution and range of numerical data in the DataFrame.

4. ndrop(): Removes specified rows or columns.

Example: df.drop("Gender", axis=1) removes the "Gender" column from the DataFrame.

5. fillna(): Fills missing values with a specified value or method (like forward filling).

Example: df.fillna(0) replaces all missing values with 0, helpful when you need to avoid NaNs for calculations.

6. groupby(): Groups data by a specified column and performs aggregations on grouped data.

Example: df.groupby("Gender").mean() calculates the average for each gender category, useful for comparison purposes.

7. merge(): Combines two DataFrames based on a common key or index.

Example: Use pd.merge(df1, df2, on="ID") to join data from two DataFrames based on an "ID" column.

8. apply(): Applies a custom function to a DataFrame or Series.

Example: df["Age"].apply(lambda x: x + 1) adds 1 to each value in the "Age" column, useful for transformations.

In [10]:
# Example:
# Sample DataFrame
data = pd.DataFrame({
    "Name": ["Alice", "Bob", "Claire", "David"],
    "Age": [25, 30, 27, 22],
    "Gender": ["Female", "Male", "Female", "Male"]
})

# Grouping by "Gender" and calculating the mean age
average_age_by_gender = data.groupby("Gender")["Age"].mean()
print(average_age_by_gender)

Gender
Female    26.0
Male      26.0
Name: Age, dtype: float64

Q6. Which of the following is mutable in nature Series, DataFrame, Panel?

Answer:

In Pandas, both Series and DataFrame are mutable, meaning that it can be modified their data, structure, or content after creation.

Breakdown:

Series: Mutable. You can change individual elements, add new data, or modify values within a Series.

DataFrame: Mutable. You can alter data in cells, add or remove columns and rows, and modify existing data.

Panel: Although Panels were three-dimensional data structures in earlier versions of Pandas (allowing data manipulation in 3D), they have since been deprecated and removed as of Pandas version 1.0. Instead, it's recommended to use MultiIndex DataFrames or xarray for multi-dimensional data. Panels were also mutable when they existed, but are no longer part of Pandas.

In practice, Series and DataFrames are commonly used for data manipulation due to their flexibility and mutability.

Q7. Create a DataFrame using multiple Series. Explain with an example.

Answer:


To create a DataFrame from multiple Series,  pass each Series as a column in a dictionary. Each Series will represent a column, and the DataFrame will use their indices as row labels if they align.

Example

Suppose we have three Series representing "Name," "Age," and "Gender" information. We will combine them to form a DataFrame.

In [11]:
# Example
import pandas as pd

# Creating Series
name_series = pd.Series(["Alice", "Bob", "Claire"])
age_series = pd.Series([25, 30, 27])
gender_series = pd.Series(["Female", "Male", "Female"])

# Creating DataFrame from multiple Series
data_frame = pd.DataFrame({
    "Name": name_series,
    "Age": age_series,
    "Gender": gender_series
})

# Displaying the DataFrame
data_frame

     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   27  Female

Explanation:

Each Series represents a column:

1. name_series becomes the "Name" column.
2. age_series becomes the "Age" column.
3. gender_series becomes the "Gender" column.

Since each Series has the same length, they align perfectly by their indices to form rows in the DataFrame.

This method is useful when data is collected separately in Series but needs to be combined into a single structure for analysis or manipulation.

**Thank You!**